# Generated by Django 4.2.7 on 2023-11-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default=None, verbose_name='Name of the event'),
            preserve_default=False,
        ),
    ]
