version: '3.7'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: dev
    volumes:
      - ./src:/src
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=socialhack"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
        - "5050:80"
    environment:
        - "PGADMIN_DEFAULT_EMAIL=admin@admin.com"
        - "PGADMIN_DEFAULT_PASSWORD=admin"
    volumes:
        - ./pgadmin_data:/var/lib/pgadmin